### PR TITLE
Test latest netCDF4

### PR DESCRIPTION
**Pull request by ocefpaf**
Just testing what happens with the latest versions.

### CODE REVIEW

**Comment by ChrisBarker-NOAA** [comment]
I got segfaults on OS-X on every combo of netcdf4 and Numpy I tried :-(

CHB

Sent from my iPhone

On Jul 17, 2016, at 9:27 AM, Filipe <notifications@github.com> wrote:

Just testing what happens with the latest versions.
------------------------------
You can view, comment on, or merge this pull request online at:

  https://github.com/sgrid/pysgrid/pull/92
Commit Summary

   - Test latest netCDF4

File Changes

   - *M* requirements.txt
   <https://github.com/sgrid/pysgrid/pull/92/files#diff-0> (2)

Patch Links:

   - https://github.com/sgrid/pysgrid/pull/92.patch
   - https://github.com/sgrid/pysgrid/pull/92.diff

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/sgrid/pysgrid/pull/92>, or mute the thread

**Comment by ocefpaf** [comment]
> I got segfaults on OS-X on every combo of netcdf4 and Numpy I tried :-(

I can run the tests with the following combination:

```shell

    curl:        7.45.0-0           
    hdf5:        1.8.15.1-2         
    libgfortran: 3.0.0-1            
    libnetcdf:   4.3.3.1-3          
    netcdf4:     1.2.1-np110py27_0  
    nomkl:       1.0-0              
    numpy:       1.10.4-py27_nomkl_2 [nomkl]
    openblas:    0.2.14-4           
    openssl:     1.0.2h-1           
    pip:         8.1.2-py27_0       
    python:      2.7.12-1           
    readline:    6.2-2              
    setuptools:  23.0.0-py27_0      
    sqlite:      3.13.0-0           
    tk:          8.5.18-0           
    wheel:       0.29.0-py27_0      
    zlib:        1.2.8-3  
```

Same as Travis-CI [logs](https://api.travis-ci.org/jobs/122862884/log.txt?deansi=true), but an update to `netcdf4 1.2.4` crashes.

**Comment by ChrisBarker-NOAA** [comment]
netcdf4:     1.2.1-np110py27_0


Same as Travis-CI logs
<https://api.travis-ci.org/jobs/122862884/log.txt?deansi=true>, but an
update to netcdf4 1.2.4 crashes.

This may be the answer -- I had failures with 1.2.2-np110 also.

Now if we could just figure out a simple test for netcdf4 that triggers
this...

Note- the failures are intermittent -- so CI could pass sometimes :-)

-CHB



You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/sgrid/pysgrid/pull/92#issuecomment-233294045>, or mute
the thread

**Comment by ChrisBarker-NOAA** [comment]
Sigh:

============================= test session starts ==============================
platform darwin -- Python 2.7.12, pytest-2.9.2, py-1.4.31, pluggy-0.3.1
rootdir: /Users/chris.barker/HAZMAT/ERD-PythonPackages/pysgrid, inifile: 
collected 83 items 

test_interpolation.py ...
test_processing_2d.py .....
test_read_netcdf.py ...................
test_sgrid.py .....................F......FFF.....Segmentation fault: 11

```
$ conda list
# packages in environment at /Users/chris.barker/miniconda2/envs/nc_sgrid:
#
curl                      7.45.0                        0  
hdf5                      1.8.15.1                      2  
libnetcdf                 4.3.3.1                       3  
mkl                       11.3.3                        0  
netcdf4                   1.2.1               np110py27_0  
numpy                     1.10.4                   py27_2  
openssl                   1.0.2h                        1  
pip                       8.1.2                    py27_0  
python                    2.7.12                        1  
readline                  6.2                           2  
setuptools                23.0.0                   py27_0  
sqlite                    3.13.0                        0  
tk                        8.5.18                        0  
wheel                     0.29.0                   py27_0  
zlib                      1.2.8                         3  
```

I think the difference with what Filipe ran is mkl -- so I"ll try that now.

**Comment by ChrisBarker-NOAA** [comment]
Darn!  tried with nomkl, and they passed!!! -- but I re-ran them a few times, and at time 4:

$ py.test
============================= test session starts ==============================
platform darwin -- Python 2.7.12, pytest-2.9.2, py-1.4.31, pluggy-0.3.1
rootdir: /Users/chris.barker/HAZMAT/ERD-PythonPackages/pysgrid, inifile: 
collected 83 items 

test_interpolation.py ...
test_processing_2d.py .....
test_read_netcdf.py ...................
test_sgrid.py ......................Segmentation fault: 11

```
$ conda list
# packages in environment at /Users/chris.barker/miniconda2/envs/nc_sgrid:
#
curl                      7.45.0                        0  
hdf5                      1.8.15.1                      2  
libnetcdf                 4.3.3.1                       3  
mkl                       11.3.3                        0  
netcdf4                   1.2.1               np110py27_0  
nomkl                     1.0                           0  
numpy                     1.10.4             py27_nomkl_2  [nomkl]
openssl                   1.0.2h                        1  
pip                       8.1.2                    py27_0  
python                    2.7.12                        1  
readline                  6.2                           2  
setuptools                23.0.0                   py27_0  
sqlite                    3.13.0                        0  
tk                        8.5.18                        0  
wheel                     0.29.0                   py27_0  
zlib                      1.2.8                         3  
```

This really sucks. I sure wish `netcdf4` had comprehensive tests :-(

**Comment by ocefpaf** [comment]
@ChrisBarker-NOAA I believe we might be chasing a red-herring here. All netCDF4-python netcdf files are written with a `with` statement. That ensures they are closed after creation. Also, each `unittest` has `setUp` and `tearDown` class that ensure the file is read, used, and closed at the end of the test suit.

BTW: I cannot get the failure in my local laptop, not even on Windows! So I am trying a few things and testing them on Travis-CI to see if I can narrow this down.

**Comment by ChrisBarker-NOAA** [comment]
Honestly, I've had various issues like this with netCDF even with with, and calling close() explicitly. Both file locking on Windows and  odd errors on OS-X (usually not seg faults, though.

I don't think netcdf4 is the least bit robust in this regard :-(

I don't know that I'll ever have the energy for it, but what we really need is comprehensive tests in the netcdf4 lib itself.

have you tried our fork:

https://github.com/NOAA-ORR-ERD/pysgrid

a bunch of new/different stuff in there, but not in the tests that are failing.

**Comment by ChrisBarker-NOAA** [comment]
I've got an idea here.

I don't think this is keeping files open that's the problem. After all,
it's totally inconsistent when or whether the segfaults happen. Plus, it's
not always a segfault -- I sometimes get other arbitrary errors.

My working theory: there is s bug in netcdf4 (probably the C lib, but maybe
the python bindings) such that if you open, write, close, read, etc a LOT
of files while running in one process, the bug finally leaks out and starts
causing problems.

Our unit tests, run by pytest, open and close a lot of files all while
running in one process.

Operational code usually only works with a few files ( though web services
may use a lot)

In any case, in this instance, and others I've dealt with, if I comment out
enough tests, it works fine. As I ad more, it starts crashing, and it
doesn't seem to matter which ones are running --they all pass fine when run
alone.

Also,

I'm pretty sure pytest runs everything in one thread, but we should make
sure -- netcdf is known not to be thread safe.

We could also look into pytest-xdist. Not for performance, but so we can
have each process run fewer tests....

-CHB





Sent from my iPhone

On Jul 18, 2016, at 4:03 PM, Filipe <notifications@github.com> wrote:

@ChrisBarker-NOAA <https://github.com/ChrisBarker-NOAA> I believe we might
be chasing a red-herring here. All netCDF4-python netcdf files are written
with a with statement. That ensures they are closed after creation. Also,
each unittest has setUp and tearDown class that ensure the file is read,
used, and closed at the end of the test suit.

BTW: I cannot get the failure in my local laptop, not even on Windows! So I
am trying a few things and testing them on Travis-CI to see if I can narrow
this down.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/sgrid/pysgrid/pull/92#issuecomment-233485075>, or mute
the thread

**Comment by ChrisBarker-NOAA** [comment]
. All netCDF4-python netcdf files are written with a with statement. That
ensures they are closed after creation.

Only if there isn't a big in the context manager. But I agree, it's
probably not as simple as an open file -- that shouldn't segfault anyway.

BTW: I cannot get the failure in my local laptop, not even on Windows! So I
am trying a few things and testing them on Travis-CI to see if I can narrow
this down.

Maybe this points to a bug on OS-X only -- that may be helpful.

-CHB

**Comment by ocefpaf** [comment]
@ayan-usgs changing the tests to use `fixtures` that encapsulates the file creation seems to solve the `segfaults` in the latest `netCDF4`. Note that the number of tests remained unchanged (79), but we could do with some test refactoring to aggregate each type of source grid into its own file.

Let me know if you want me to clean this up. It may be a little messy due to the change from `unittest` classes to `pytest` functions.

**Comment by ChrisBarker-NOAA** [comment]
WHoo Hoo!

I just ran the tests with this code, and got all the tests to pass multiple times -- looking good. 

This is with:
netcdf4                   1.2.1               np110py27_0  

but at least it's a start.

```
$ conda list
# packages in environment at /Users/chris.barker/miniconda2/envs/pysgrid:
#
blas                      1.1                    openblas    conda-forge
cell_tree2d               0.2.0               np110py27_0    conda-forge
flake8                    2.6.2                    py27_0    conda-forge
funcsigs                  1.0.2                    py27_0    conda-forge
libgfortran               3.0.0                         0    conda-forge
mccabe                    0.5.0                    py27_0    conda-forge
mock                      2.0.0                    py27_0    conda-forge
nose                      1.3.7                    py27_0    conda-forge
numpy                     1.10.4          py27_blas_openblas_201  [blas_openblas]  conda-forge
openblas                  0.2.18                        3    conda-forge
pycodestyle               2.0.0                    py27_0    conda-forge
pyflakes                  1.2.3                    py27_0    conda-forge
pytest                    2.9.2                    py27_0    conda-forge
six                       1.10.0                   py27_0    conda-forge
curl                      7.45.0                        0  
hdf5                      1.8.15.1                      2  
libnetcdf                 4.3.3.1                       3  
netcdf4                   1.2.1               np110py27_0  
openssl                   1.0.2h                        1  
pbr                       1.10.0                   py27_0  
pip                       8.1.2                    py27_0  
py                        1.4.31                   py27_0  
python                    2.7.12                        1  
readline                  6.2                           2  
setuptools                23.0.0                   py27_0  
sqlite                    3.13.0                        0  
tk                        8.5.18                        0  
wheel                     0.29.0                   py27_0  
zlib                      1.2.8                         3  
```

**Comment by ocefpaf** [comment]
What @ayan-usgs had before was correct, but we probably hit a bug in mix of `unittest`, `netCDF4`, `with` statements, etc. With `pytest` everything is encapsulated and (probably) safer. Note that this patter can be used anywhere were netCDF4 objects or files are needed:

```python
@pytest.yield_fixture
def crate_nc(fname):
    nc = Dataset(fname, 'w')
    .
    .
    .
    nc.sync()
    yield nc
    nc.close()
    os.remove(fname)
```

Another option is what I implemented in `pyugrid` some time ago, but I believe this pattern here is better and we should probably use it there too.

**Comment by ayan-usgs** [comment]
:+1:

**Comment by ChrisBarker-NOAA** [comment]
On Wed, Jul 20, 2016 at 9:37 AM, Filipe <notifications@github.com> wrote:

> What @ayan-usgs <https://github.com/ayan-usgs> had before was correct,
> but we probably hit a bug in mix of unittest, netCDF4, with statements,
> etc.
>
indeed -- I couldn't find any errors.


> With pytest everything is encapsulated and (probably) safer.
>
and it's working. I"m still pretty convinced that it was hitting a bug in
netcdf4 somewhere -- it had non-deterministic results, even though py.test
presumably calls everything in the same order. But apparently it was
stressing it in a way that most applications don't

I've tried to reproduce the effect in a simpler case, no luck yet -- I
probably won't try much harder

(though I have hit similar non-deterministic issues in tests for other
projects.)


> Note that this patter can be used anywhere were netCDF4 objects or files
> are needed:
>
nice! and it did seem to clear up the problem -- great. I think this really
shoudl be easy to find as a recipe somewhere...

> @pytest.yield_fixturedef crate_nc(fname):
>     nc = Dataset(fname, 'w')
>     .
>     .
>     .
>     nc.sync()
>     yield nc
>     nc.close()
>     os.remove(fname)
>
> Another option is what I implemented in pyugrid some time ago, but I
> believe this pattern here is better and we should probably use it there too.
>
I'll try to remember to go clean those up next time I touch those tests...

-CHB

**Pull request merged**
