### PR TITLE
Fix #60

### LINKED ISSUE #60: Pinned versions
Pinning the requirements versions

```
netCDF4==1.1.8
numpy==1.9.2
```

and [enforcing](https://github.com/sgrid/pysgrid/blob/master/setup.py#L7) them at install time is creating makes it a hellish nightmare to install `netCDF4 1.1.9` and/or `numpy 1.8`.  Both are perfectly OK with `pysgrid` BTW!

Please consider relaxing the version constraint unless a real version issue exists.

### PR DESCRIPTION
**Pull request by ocefpaf**
This PR relaxes the pinned versions for `numpy` and `netCDF4-python`.  Let's see if I can break a few tests!

### CODE REVIEW

**Comment by ocefpaf** [comment]
Ran 84 tests in 1.327s !

@ayan-usgs I could not break anything with latest `netCDF4-python`.

We could create a test matrix to be through, but I don't see anything in the code that can break with the  current used versions of `numpy` (`>1.7`) and `netCDF4-python` (`>1.0.0`)

**Comment by ocefpaf** [comment]
I went ahead and added an extra commit that prevents importing the module before it is installed.  That way we do not need to pre-install the dependencies just to run `setup.py`

**Comment by ayan-usgs** [comment]
@ocefpaf,

I don't see a need for a matrix at this point. The presence/absence of version numbers on dependencies strikes me as a double-edged sword. 

Thanks for making the changes. This PR looks good to go.

**Comment by ocefpaf** [comment]
> The presence/absence of version numbers on dependencies strikes me as a double-edged sword.

As long as it is killing dragons and just scratching us we are good :wink:

**Comment by ocefpaf** [comment]
@ayan-usgs can we get a new release?

**Comment by ocefpaf** [comment]
Never mind.  I just saw I have admin rights here.  I can do it.  Thanks @ayan-usgs!

**Pull request merged**
