### PR TITLE
simplified searching by location and standard name

### PR DESCRIPTION
**Pull request by ayan-usgs**

### CODE REVIEW

**Comment by ayan-usgs** [comment]
@ocefpaf,

Would you be able to give this PR a quick look?

**Comment by ocefpaf** [comment]
If you can wait until the 21st I can.  I won't have a laptop until then :-(
Em 19/05/2015 15:03, "ayan-usgs" <notifications@github.com> escreveu:

**Comment by ayan-usgs** [comment]
@ocefpaf,

No worries. I can reassign.

**Comment by kwilcox** [comment]
This function might help out: https://github.com/axiom-data-science/pyaxiom/blob/master/README.md#retrieving-variables-by-attributes-and-valuescallables

Easily extractable, adding pyaxiom as a req. would be overkill.

https://github.com/axiom-data-science/pyaxiom/blob/master/pyaxiom/netcdf/dataset.py#L10

**Comment by mhines-usgs** [comment]
:+1:

**Comment by ocefpaf** [comment]
@kwilcox I know that this Class is tiny, but would you consider making it its own separate module?   I can see lots of use for a `ncDataset++` (patent pending :wink: )

**Pull request merged**
