### PR TITLE
Use setuptools for packaging

### PR DESCRIPTION
**Pull request by kwilcox**

### CODE REVIEW

**Comment by ocefpaf** [comment]
:+1:  (Except for the pep8 infringements! :stuck_out_tongue_winking_eye: )

**Comment by kwilcox** [comment]
@ocefpaf I code with some rules ignored!

```json
"pep8_ignore":  [
        "E501", "E221", "E203", "E201", "E124", "E202", "E251", "W293", "W291"
],
```

**Comment by ocefpaf** [comment]
I understand all but `E221`.  That kind of syntax reminds me of my MatlabTM days...

**Comment by kwilcox** [comment]
but.. but...

**Comment by ocefpaf** [comment]
OK, OK. Jake knows best.

**Comment by ayan-usgs** [comment]
@kwilcox,

Good to go!

**Pull request merged**
