### PR TITLE
removed time handling and switched to using miniconda for travis tests

### PR DESCRIPTION
**Pull request by ayan-usgs**

### CODE REVIEW

**Comment by ayan-usgs** [comment]
Removed time variable handling per issue #41 and went to anaconda for testing per a suggestion in #42.

**Comment by ayan-usgs** [comment]
@ocefpaf,

Can you give this PR a look when you get a chance?

Thanks!

**Comment by ocefpaf** [comment]
Sure, but that will take a while. I am traveling and without my laptop.
Em 18/05/2015 11:11, "ayan-usgs" <notifications@github.com> escreveu:

**Comment by ayan-usgs** [comment]
@ocefpaf,

No worries. I can reassign the PR; there's no need to work on this while your traveling. 

Safe travels! :smiley_cat:

**Comment by ayan-usgs** [comment]
@mhines-usgs,

Can you give this a quick look when you have some time?

Thanks!

**Comment by mhines-usgs** [comment]
@ayan-usgs I don't see any reason this can't be merged! :ship: :it:

**Pull request merged**
